services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.prod
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8071:8000"
    env_file:
      - .env
    depends_on:
      - mysql
    command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
  vite:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8072:8072"
    command: bash -c "npm install && npm run dev -- --host=0.0.0.0"
    depends_on:
      - app

  mysql:
    image: mariadb
    restart: unless-stopped
    ports:
      - "8073:3306"
    volumes:
      - clinica-estetica-gestao:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}


volumes:
  clinica-estetica-gestao:
